# Generated by Django 5.0.6 on 2024-10-10 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_menuitem_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorysmenu',
            name='color',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='categorysmenu',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='categories/'),
        ),
    ]
