# Generated by Django 5.0.6 on 2024-10-13 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_categorysmenu_color_categorysmenu_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorysmenu',
            name='size',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
