# Generated by Django 5.0.6 on 2024-10-13 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_categorysmenu_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorysmenu',
            name='price',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
