# Generated by Django 5.0.6 on 2024-10-13 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_categorysmenu_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorysmenu',
            name='price',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
