# Generated by Django 5.0.6 on 2024-10-14 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_menuitem_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='user',
        ),
        migrations.DeleteModel(
            name='Images',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
