# Generated by Django 5.0.6 on 2024-10-15 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_remove_product_category_remove_product_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='categories',
        ),
        migrations.DeleteModel(
            name='CategorysMenu',
        ),
    ]
