# Generated by Django 5.0.6 on 2024-10-30 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoriesItems', '0010_remove_category_menuitemname_and_more'),
        ('main', '0016_remove_menuitem_categories_delete_categorysmenu'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='boyutlar',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menuitem',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='menuItem', to='categoriesItems.category'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='collections',
            field=models.ManyToManyField(blank=True, related_name='menuItem', to='categoriesItems.collection'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='colors',
            field=models.ManyToManyField(blank=True, related_name='menuItem', to='categoriesItems.color'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='compatibles',
            field=models.ManyToManyField(blank=True, related_name='menuItem', to='categoriesItems.compatible'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='metalNames',
            field=models.ManyToManyField(blank=True, related_name='menuItem', to='categoriesItems.metalname'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='metals',
            field=models.ManyToManyField(blank=True, related_name='menuItem', to='categoriesItems.metal'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='priceRange',
            field=models.ManyToManyField(blank=True, related_name='menuItem', to='categoriesItems.pricerange'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='sizes',
            field=models.ManyToManyField(blank=True, related_name='menuItem', to='categoriesItems.size'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='stones',
            field=models.ManyToManyField(blank=True, related_name='menuItem', to='categoriesItems.stones'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='themes',
            field=models.ManyToManyField(blank=True, related_name='menuItem', to='categoriesItems.theme'),
        ),
    ]
