# Generated by Django 5.0.6 on 2024-10-16 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categoriesItems', '0005_color_color'),
        ('main', '0016_remove_menuitem_categories_delete_categorysmenu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('available', models.BooleanField(default=True)),
                ('active', models.BooleanField(default=False)),
                ('colors', models.ManyToManyField(blank=True, related_name='products', to='categoriesItems.color')),
                ('mainCategories', models.ManyToManyField(blank=True, related_name='MainCategoriesProducts', to='main.menuitem')),
                ('sizes', models.ManyToManyField(blank=True, related_name='products', to='categoriesItems.size')),
            ],
        ),
    ]
