# Generated by Django 5.0.6 on 2024-10-16 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoriesItems', '0005_color_color'),
        ('productItems', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='products', to='categoriesItems.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='collections',
            field=models.ManyToManyField(blank=True, related_name='products', to='categoriesItems.collection'),
        ),
        migrations.AddField(
            model_name='product',
            name='compatibles',
            field=models.ManyToManyField(blank=True, related_name='products', to='categoriesItems.compatible'),
        ),
        migrations.AddField(
            model_name='product',
            name='metals',
            field=models.ManyToManyField(blank=True, related_name='products', to='categoriesItems.metal'),
        ),
        migrations.AddField(
            model_name='product',
            name='priceRange',
            field=models.ManyToManyField(blank=True, related_name='products', to='categoriesItems.pricerange'),
        ),
        migrations.AddField(
            model_name='product',
            name='themes',
            field=models.ManyToManyField(blank=True, related_name='products', to='categoriesItems.theme'),
        ),
    ]
