# Generated by Django 5.0.6 on 2024-10-23 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoriesItems', '0007_stones'),
        ('productItems', '0005_product_metalnames'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stones',
            field=models.ManyToManyField(blank=True, related_name='products', to='categoriesItems.stones'),
        ),
    ]
