# Generated by Django 5.0.6 on 2024-10-23 12:17

import productItems.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productItems', '0006_product_stones'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='code',
            field=models.CharField(default=productItems.models.generate_unique_code, max_length=8, unique=True),
        ),
    ]
