# Generated by Django 5.0.6 on 2024-10-24 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoriesItems', '0008_family'),
        ('productItems', '0008_product_boyutlar'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='family',
            field=models.ManyToManyField(blank=True, related_name='products', to='categoriesItems.family'),
        ),
    ]
