# Generated by Django 5.0.6 on 2024-10-15 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoriesItems', '0004_remove_category_level_remove_category_lft_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='color',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
