# Generated by Django 5.0.6 on 2024-10-30 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoriesItems', '0008_family'),
        ('main', '0016_remove_menuitem_categories_delete_categorysmenu'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='menuItemName',
            field=models.ManyToManyField(blank=True, related_name='menuItemCategory', to='main.menuitem'),
        ),
        migrations.AddField(
            model_name='collection',
            name='menuItemName',
            field=models.ManyToManyField(blank=True, related_name='menuItemCollection', to='main.menuitem'),
        ),
        migrations.AddField(
            model_name='color',
            name='menuItemName',
            field=models.ManyToManyField(blank=True, related_name='menuItemColor', to='main.menuitem'),
        ),
        migrations.AddField(
            model_name='compatible',
            name='menuItemName',
            field=models.ManyToManyField(blank=True, related_name='menuItemCompatible', to='main.menuitem'),
        ),
        migrations.AddField(
            model_name='family',
            name='menuItemName',
            field=models.ManyToManyField(blank=True, related_name='menuItemFamily', to='main.menuitem'),
        ),
        migrations.AddField(
            model_name='metal',
            name='menuItemName',
            field=models.ManyToManyField(blank=True, related_name='menuItemMetal', to='main.menuitem'),
        ),
        migrations.AddField(
            model_name='metalname',
            name='menuItemName',
            field=models.ManyToManyField(blank=True, related_name='menuItemMetalName', to='main.menuitem'),
        ),
        migrations.AddField(
            model_name='pricerange',
            name='menuItemName',
            field=models.ManyToManyField(blank=True, related_name='menuItemPriceRange', to='main.menuitem'),
        ),
        migrations.AddField(
            model_name='size',
            name='menuItemName',
            field=models.ManyToManyField(blank=True, related_name='menuItemSize', to='main.menuitem'),
        ),
        migrations.AddField(
            model_name='stones',
            name='menuItemName',
            field=models.ManyToManyField(blank=True, related_name='menuItemStones', to='main.menuitem'),
        ),
        migrations.AddField(
            model_name='theme',
            name='menuItemName',
            field=models.ManyToManyField(blank=True, related_name='menuItemTheme', to='main.menuitem'),
        ),
    ]
